var e;e||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},e),k=(a,b)=>{throw b;},p="";"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src);p=p.startsWith("blob:")?"":p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1);var ba=e.print||console.log.bind(console),r=e.printErr||console.error.bind(console);Object.assign(e,aa);aa=null;e.quit&&(k=e.quit);var t;e.wasmBinary&&(t=e.wasmBinary);
var ca,u=!1,v,w,da,ea,x,y,A,B,fa=[],ha=[],ia=[],ja=[];function ka(){var a=e.preRun.shift();fa.unshift(a)}var C=0,D=null,E=null;function F(a){e.onAbort?.(a);a="Aborted("+a+")";r(a);u=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var la=a=>a.startsWith("data:application/octet-stream;base64,"),G;function ma(a){if(a==G&&t)return new Uint8Array(t);throw"both async and sync fetching of the wasm failed";}
function na(a){return t||"function"!=typeof fetch?Promise.resolve().then(()=>ma(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>ma(a))}function oa(a,b,c){return na(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);F(d)})}
function pa(a,b){var c=G;t||"function"!=typeof WebAssembly.instantiateStreaming||la(c)||"function"!=typeof fetch?oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){r(`wasm streaming compile failed: ${f}`);r("falling back to ArrayBuffer instantiation");return oa(c,a,b)}))}var qa={547884:a=>{a=H(a);console.log(a);window.electronAPI.sendMessageToPresenter(a)}};
function ra(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var I=a=>{for(;0<a.length;)a.shift()(e)},sa=e.noExitRuntime||!0,ta=new TextDecoder("utf8"),H=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&w[c];)++c;return ta.decode(w.subarray(a,c))};e.UTF8ToString=H;class ua{constructor(a){this.pa=a-24}}var va=0,wa=0,J=[],K=[],xa,ya=a=>{var b=K[a];b||(a>=K.length&&(K.length=a+1),K[a]=b=xa.get(a));return b},L=0,N=[];
function za(){if(navigator.userActivation?navigator.userActivation.isActive:L&&Aa.Fa)for(var a=0;a<N.length;++a){var b=N[a];N.splice(a,1);--a;b.Ra(...b.Ga)}}var O=[];function Ba(a){var b=O[a];b.target.removeEventListener(b.ra,b.ta,b.xa);O.splice(a,1)}function Ca(a){if(!a.target)return-4;if(a.za)a.ta=function(c){++L;Aa=a;za();a.Da(c);za();--L},a.target.addEventListener(a.ra,a.ta,a.xa),O.push(a);else for(var b=0;b<O.length;++b)O[b].target==a.target&&O[b].ra==a.ra&&Ba(b--);return 0}
var Aa,Da,Ea=[0,document,window],P=a=>{a=2<a?H(a):a;return Ea[a]||document.querySelector(a)},Q=(a,b,c)=>{var d=w;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}},Ga=(a,b,
c,d,f,g)=>{Da||=Fa(176);a={target:P(a),ra:g,za:d,Da:h=>{var m=Da;B[m>>3]=h.timeStamp;var n=m>>2;x[n+2]=h.location;x[n+3]=h.ctrlKey;x[n+4]=h.shiftKey;x[n+5]=h.altKey;x[n+6]=h.metaKey;x[n+7]=h.repeat;x[n+8]=h.charCode;x[n+9]=h.keyCode;x[n+10]=h.which;Q(h.key||"",m+44,32);Q(h.code||"",m+76,32);Q(h.char||"",m+108,32);Q(h.locale||"",m+140,32);ya(d)(f,m,b)&&h.preventDefault()},xa:c};return Ca(a)},Ha=1,Ia=[],R=[],S=[],T=[],U=[],Ja=4,V=a=>{for(var b=Ha++,c=a.length;c<b;c++)a[c]=null;return b},La=(a,b,c,d)=>
{for(var f=0;f<a;f++){var g=W[c](),h=g&&V(d);g?(g.name=h,d[h]=g):Ka||=1282;x[b+4*f>>2]=h}},Na=(a,b)=>{a.pa||(a.pa=a.getContext,a.getContext=function(d,f){f=a.pa(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.ua?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Ma(c,b):0},Ma=(a,b)=>{var c=V(U);b={handle:c,attributes:b,version:b.ua,ya:a};a.canvas&&(a.canvas.Ea=b);U[c]=b;return c},Ka,X,Oa=["default","low-power","high-performance"],Pa=[null,[],[]],Qa=a=>"]"==a.slice(-1)&&
a.lastIndexOf("["),Ra=a=>{a-=5120;return 0==a?v:1==a?w:2==a?da:4==a?x:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?y:ea},Sa=a=>{var b=W.Ba;if(b){var c=b.qa[a];"number"==typeof c&&(b.qa[a]=c=W.getUniformLocation(b,b.va[a]+(0<c?`[${c}]`:"")));return c}Ka||=1282};function Ta(a){W.pixelStorei(37440,!0);W.texImage2D(3553,0,6408,6408,5121,a);W.pixelStorei(37440,!1)}
var W,Ua={d:(a,b,c,d)=>{F(`Assertion failed: ${H(a)}, at: `+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},u:(a,b,c)=>{var d=new ua(a);y[d.pa+16>>2]=0;y[d.pa+4>>2]=b;y[d.pa+8>>2]=c;va=a;wa++;throw va;},v:()=>{F("")},w:()=>1,z:(a,b,c)=>w.copyWithin(a,b,b+c),C:(a,b,c)=>{J.length=0;for(var d;d=w[b++];){var f=105!=d;f&=112!=d;c+=f&&c%8?4:0;J.push(112==d?y[c>>2]:105==d?x[c>>2]:B[c>>3]);c+=f?8:4}return qa[a](...J)},t:()=>devicePixelRatio,y:()=>performance.now(),b:()=>Math.random(),k:(a,b)=>{function c(d){ya(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},x:()=>!1,r:(a,b,c)=>{a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},s:(a,b,c)=>{a=P(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},U:(a,b,c,d)=>Ga(a,b,c,d,2,"keydown"),N:(a,b,c,d)=>Ga(a,b,c,d,3,"keyup"),V:a=>{throw H(a);},T:(a,b)=>{b>>=2;b={alpha:!!x[b],depth:!!x[b+1],stencil:!!x[b+2],antialias:!!x[b+3],premultipliedAlpha:!!x[b+4],preserveDrawingBuffer:!!x[b+5],powerPreference:Oa[x[b+6]],failIfMajorPerformanceCaveat:!!x[b+
7],ua:x[b+8],Oa:x[b+9],Ja:x[b+10],Ca:x[b+11],Pa:x[b+12],Qa:x[b+13]};a=P(a);return!a||b.Ca?0:Na(a,b)},S:a=>{X=U[a];e.Ha=W=X?.ya;return!a||W?0:-5},i:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var h=y[b>>2],m=y[b+4>>2];b+=8;for(var n=0;n<m;n++){var l=w[h+n],q=Pa[a];if(0===l||10===l){for(l=0;q[l]&&!(NaN<=l);)++l;l=ta.decode(q.buffer?q.subarray(0,l):new Uint8Array(q.slice(0,l)));(1===a?ba:r)(l);q.length=0}else q.push(l)}f+=m}y[d>>2]=f;return 0},A:function(a,b,c){function d(){for(var h=g.getImageData(0,0,f.width,
f.height),m=new Uint32Array(h.data.buffer),n=h.width-1;0<n;--n)for(var l=n;l<m.length;l+=h.width)if(m[l])return n}32>=a&&(a=105);32>=b&&(b=105);b=String.fromCharCode(b);var f=document.createElement("canvas");f.height=c;f.width=3*c;var g=f.getContext("2d");g.font=c+"px Arial Unicode";g.fillText(b,0,f.height-7);c=d();g.fillText(String.fromCharCode(a)+b,0,f.height-7);return d()-c},n:(a,b)=>{W.attachShader(R[a],T[b])},Q:(a,b,c)=>{W.bindAttribLocation(R[a],b,H(c))},J:(a,b)=>{35051==a?W.Ia=b:35052==a&&
(W.Aa=b);W.bindBuffer(a,Ia[b])},c:(a,b)=>{W.bindTexture(a,S[b])},L:(a,b)=>W.blendFunc(a,b),I:(a,b,c,d)=>{2<=X.version?c&&b?W.bufferData(a,w,d,c,b):W.bufferData(a,b,d):W.bufferData(a,c?w.subarray(c,c+b):b,d)},E:a=>W.clear(a),F:(a,b,c,d)=>W.clearColor(a,b,c,d),o:a=>{W.compileShader(T[a])},R:()=>{var a=V(R),b=W.createProgram();b.name=a;b.Na=b.La=b.Ma=0;b.sa=1;R[a]=b;return a},q:a=>{var b=V(T);T[b]=W.createShader(a);return b},e:(a,b,c)=>{W.drawArrays(a,b,c)},M:a=>W.enable(a),G:a=>{W.enableVertexAttribArray(a)},
K:(a,b)=>{La(a,b,"createBuffer",Ia)},h:(a,b)=>{La(a,b,"createTexture",S)},m:(a,b)=>{b=H(b);if(a=R[a]){var c=a,d=c.qa,f=c.wa,g;if(!d)for(c.qa=d={},c.va={},g=0;g<W.getProgramParameter(c,35718);++g){var h=W.getActiveUniform(c,g);var m=h.name;h=h.size;var n=Qa(m);n=0<n?m.slice(0,n):m;var l=c.sa;c.sa+=h;f[n]=[h,l];for(m=0;m<h;++m)d[l]=m,c.va[l++]=n}c=a.qa;d=0;f=b;g=Qa(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.wa[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||W.getUniformLocation(a,b)))return d}else Ka||=
1281;return-1},P:a=>{a=R[a];W.linkProgram(a);a.qa=0;a.wa={}},j:(a,b)=>{3317==a&&(Ja=b);W.pixelStorei(a,b)},p:(a,b,c,d)=>{for(var f="",g=0;g<b;++g)f+=H(y[c+4*g>>2],d?y[d+4*g>>2]:void 0);W.shaderSource(T[a],f)},l:(a,b,c,d,f,g,h,m,n)=>{if(2<=X.version){if(W.Aa){W.texImage2D(a,b,c,d,f,g,h,m,n);return}if(n){var l=Ra(m);n>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);W.texImage2D(a,b,c,d,f,g,h,m,l,n);return}}if(n){l=Ra(m);var q=Ja;q=f*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[h-6402]||1)*
l.BYTES_PER_ELEMENT+q-1&-q);n=l.subarray(n>>>31-Math.clz32(l.BYTES_PER_ELEMENT),n+q>>>31-Math.clz32(l.BYTES_PER_ELEMENT))}else n=null;W.texImage2D(a,b,c,d,f,g,h,m,n)},a:(a,b,c)=>W.texParameteri(a,b,c),f:(a,b,c,d,f)=>{W.uniform4f(Sa(a),b,c,d,f)},g:(a,b,c,d)=>{2<=X.version?b&&W.uniformMatrix4fv(Sa(a),!!c,A,d>>2,16*b):(b=A.subarray(d>>2,d+64*b>>2),W.uniformMatrix4fv(Sa(a),!!c,b))},O:a=>{a=R[a];W.useProgram(a);W.Ba=a},H:(a,b,c,d,f,g)=>{W.vertexAttribPointer(a,b,c,!!d,f,g)},D:function(a,b,c,d){var f=new Image;
f.onload=function(){y[c>>2]=f.width;y[d>>2]=f.height;W.bindTexture(3553,S[a]);Ta(f)};f.src=H(b)},B:function(a,b,c){var d=document.createElement("canvas");d.width=d.height=b;var f=d.getContext("2d");f.fillStyle="black";f.Ka="copy";f.globalAlpha=0;f.fillRect(0,0,d.width,d.height);f.globalAlpha=1;f.fillStyle="white";f.font=b+"px Arial Unicode";c&&(f.shadowColor="black",f.shadowOffsetX=2,f.shadowOffsetY=2,f.shadowBlur=3,f.strokeStyle="gray",f.strokeText(String.fromCharCode(a),0,d.height-7));f.fillText(String.fromCharCode(a),
0,d.height-7);Ta(d)}},Y=function(){function a(c){Y=c.exports;ca=Y.W;c=ca.buffer;e.HEAP8=v=new Int8Array(c);e.HEAP16=da=new Int16Array(c);e.HEAPU8=w=new Uint8Array(c);e.HEAPU16=ea=new Uint16Array(c);e.HEAP32=x=new Int32Array(c);e.HEAPU32=y=new Uint32Array(c);e.HEAPF32=A=new Float32Array(c);e.HEAPF64=B=new Float64Array(c);xa=Y.ha;ha.unshift(Y.X);C--;e.monitorRunDependencies?.(C);0==C&&(null!==D&&(clearInterval(D),D=null),E&&(c=E,E=null,c()));return Y}var b={a:Ua};C++;e.monitorRunDependencies?.(C);if(e.instantiateWasm)try{return e.instantiateWasm(b,
a)}catch(c){return r(`Module.instantiateWasm callback failed with error: ${c}`),!1}G||=la("remote.wasm")?"remote.wasm":e.locateFile?e.locateFile("remote.wasm",p):p+"remote.wasm";pa(b,function(c){a(c.instance)});return{}}(),Fa=a=>(Fa=Y.Y)(a);e._free=a=>(e._free=Y.Z)(a);e._send_presenter_msg=a=>(e._send_presenter_msg=Y._)(a);e._get_remote_mac=()=>(e._get_remote_mac=Y.$)();e._fake_presenter_state_dark=()=>(e._fake_presenter_state_dark=Y.aa)();e._init_webgl=(a,b)=>(e._init_webgl=Y.ba)(a,b);
e._set_animation_frame_callback=a=>(e._set_animation_frame_callback=Y.ca)(a);e._clear_screen=(a,b,c,d)=>(e._clear_screen=Y.da)(a,b,c,d);e._fill_image_tag=(a,b,c)=>(e._fill_image_tag=Y.ea)(a,b,c);e._load_image_by_tag=(a,b,c,d)=>(e._load_image_by_tag=Y.fa)(a,b,c,d);var Va=e._main=(a,b)=>(Va=e._main=Y.ga)(a,b);e._rand01=()=>(e._rand01=Y.ia)();e._fill_solid_rectangle=(a,b,c,d,f,g,h,m)=>(e._fill_solid_rectangle=Y.ja)(a,b,c,d,f,g,h,m);
e._fill_image=(a,b,c,d,f,g,h,m)=>(e._fill_image=Y.ka)(a,b,c,d,f,g,h,m);e._fill_text=(a,b,c,d,f,g,h,m,n,l)=>(e._fill_text=Y.la)(a,b,c,d,f,g,h,m,n,l);var Wa=a=>(Wa=Y.ma)(a),Xa=a=>(Xa=Y.na)(a),Ya=()=>(Ya=Y.oa)();
e.ccall=(a,b,c,d)=>{var f={string:l=>{var q=0;if(null!==l&&void 0!==l&&0!==l){for(var z=q=0;z<l.length;++z){var M=l.charCodeAt(z);127>=M?q++:2047>=M?q+=2:55296<=M&&57343>=M?(q+=4,++z):q+=3}q+=1;z=Xa(q);Q(l,z,q);q=z}return q},array:l=>{var q=Xa(l.length);v.set(l,q);return q}};a=e["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var n=f[c[m]];n?(0===h&&(h=Ya()),g[m]=n(d[m])):g[m]=d[m]}c=a(...g);return c=function(l){0!==h&&Wa(h);return"string"===b?H(l):"boolean"===b?!!l:l}(c)};var Z;
E=function Za(){Z||$a();Z||(E=Za)};
function $a(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!u)){I(ha);I(ia);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(ab){var b=Va;try{var c=b(0,0);sa||(e.onExit?.(c),u=!0);k(c,new ra(c))}catch(d){d instanceof ra||"unwind"==d||k(1,d)}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),ja.unshift(b);I(ja)}}if(!(0<C)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ka();I(fa);0<C||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var ab=!0;e.noInitialRun&&(ab=!1);$a();
