// This file was generated by generate.py on 2024-06-12 10:10:36.127141

#pragma once

#include <images/movie-camera_1f3a5.h> 
#include <images/top-hat_1f3a9.h> 
#include <images/pinched-fingers_1f90c.h> 
#include <images/laptop_1f4bb.h> 
#include <images/pool-8-ball_1f3b1.h> 
#include <images/airplane_2708-fe0f.h> 
#include <images/crown_1f451.h> 
#include <images/roller-skate_1f6fc.h> 
#include <images/yarn_1f9f6.h> 
#include <images/smiling-face-with-halo_1f607.h> 
#include <images/alien-monster_1f47e.h> 
#include <images/disguised-face_1f978.h> 
#include <images/vulcan-salute_1f596-1f3fe_1f3fe.h> 
#include <images/hammer_1f528.h> 
#include <images/money-bag_1f4b0.h> 
#include <images/trumpet_1f3ba.h> 
#include <images/basketball_1F3C0.h> 
#include <images/drum_1f941.h> 
#include <images/astonished-face_1f632.h> 
#include <images/ghost_1f47b.h> 
#include <images/disappointed-face_1f61e.h> 
#include <images/motorcycle_1f3cd-fe0f.h> 
#include <images/ambulance_1f691.h> 
#include <images/bell_1f514.h> 
#include <images/carousel-horse_1f3a0.h> 
#include <images/ferris-wheel_1f3a1.h> 
#include <images/abacus_1f9ee.h> 
#include <images/exploding-head_1f92f.h> 
#include <images/boxing-glove_1f94a.h> 
#include <images/clown-face_1f921.h> 
#include <images/rocket_1f680.h> 
#include <images/volleyball_1f3d0.h> 
#include <images/loudly-crying-face_1f62d.h> 
#include <images/kissing-face_1f617.h> 
#include <images/zipper-mouth-face_1f910.h> 
#include <images/anchor_2693.h> 
#include <images/moai_1f5ff.h> 
#include <images/alarm-clock_23f0.h> 
#include <images/accordion_1fa97.h> 
#include <images/cold-face_1f976.h> 
#include <images/guitar_1f3b8.h> 
#include <images/nauseated-face_1f922.h> 
#include <images/alien_1f47d.h> 
#include <images/books_1f4da.h> 
#include <images/light-bulb_1f4a1.h> 
#include <images/flushed-face_1f633.h> 
#include <images/ring_1f48d.h> 
#include <images/skull_1f480.h> 
#include <images/locomotive_1f682.h> 
#include <images/cowboy-hat-face_1f920.h> 
#include <images/pile-of-poo_1f4a9.h> 
#include <images/luggage_1f9f3.h> 
#include <images/hiking-boot_1f97e.h> 
#include <images/sleeping-face_1f634.h> 
#include <images/dizzy-face_1f635.h> 
#include <images/face-screaming-in-fear_1f631.h> 
#include <images/face-with-monocle_1f9d0.h> 
#include <images/backpack_1f392.h> 
#include <images/circus-tent_1f3aa.h> 
#include <images/pencil_270f-fe0f.h> 
#include <images/flying-saucer_1f6f8.h> 
#include <images/bicycle_1f6b2.h> 
#include <images/face-vomiting_1f92e.h> 
#include <images/tractor_1f69c.h> 
#include <images/money-with-wings_1f4b8.h> 
#include <images/pleading-face_1f97a.h> 
#include <images/teddy-bear_1f9f8.h> 
#include <images/bus_1f68c.h> 
#include <images/nerd-face_1f913.h> 
#include <images/sailboat_26f5.h> 
#include <images/helicopter_1f681.h> 
#include <images/face-with-raised-eyebrow_1f928.h> 
#include <images/ok-hand_1f44c.h> 
#include <images/robot_1f916.h> 
#include <images/wheel_1f6de.h> 
#include <images/candle_1f56f-fe0f.h> 
#include <images/smiling-face-with-horns_1f608.h> 
#include <images/telephone_260e-fe0f.h> 
#include <images/anguished-face_1f627.h> 

#define INCLUDE_ALL_IMAGES \
    const RemoteGraphic_t* EMOJIS_127909 = &Graphics_movie_camera_1f3a5; \
    const RemoteGraphic_t* EMOJIS_127913 = &Graphics_top_hat_1f3a9; \
    const RemoteGraphic_t* EMOJIS_129292 = &Graphics_pinched_fingers_1f90c; \
    const RemoteGraphic_t* EMOJIS_128187 = &Graphics_laptop_1f4bb; \
    const RemoteGraphic_t* EMOJIS_127921 = &Graphics_pool_8_ball_1f3b1; \
    const RemoteGraphic_t* EMOJIS_9992 = &Graphics_airplane_2708_fe0f; \
    const RemoteGraphic_t* EMOJIS_128081 = &Graphics_crown_1f451; \
    const RemoteGraphic_t* EMOJIS_128764 = &Graphics_roller_skate_1f6fc; \
    const RemoteGraphic_t* EMOJIS_129526 = &Graphics_yarn_1f9f6; \
    const RemoteGraphic_t* EMOJIS_128519 = &Graphics_smiling_face_with_halo_1f607; \
    const RemoteGraphic_t* EMOJIS_128126 = &Graphics_alien_monster_1f47e; \
    const RemoteGraphic_t* EMOJIS_129400 = &Graphics_disguised_face_1f978; \
    const RemoteGraphic_t* EMOJIS_128406 = &Graphics_vulcan_salute_1f596_1f3fe_1f3fe; \
    const RemoteGraphic_t* EMOJIS_128296 = &Graphics_hammer_1f528; \
    const RemoteGraphic_t* EMOJIS_128176 = &Graphics_money_bag_1f4b0; \
    const RemoteGraphic_t* EMOJIS_127930 = &Graphics_trumpet_1f3ba; \
    const RemoteGraphic_t* EMOJIS_127936 = &Graphics_basketball_1F3C0; \
    const RemoteGraphic_t* EMOJIS_129345 = &Graphics_drum_1f941; \
    const RemoteGraphic_t* EMOJIS_128562 = &Graphics_astonished_face_1f632; \
    const RemoteGraphic_t* EMOJIS_128123 = &Graphics_ghost_1f47b; \
    const RemoteGraphic_t* EMOJIS_128542 = &Graphics_disappointed_face_1f61e; \
    const RemoteGraphic_t* EMOJIS_127949 = &Graphics_motorcycle_1f3cd_fe0f; \
    const RemoteGraphic_t* EMOJIS_128657 = &Graphics_ambulance_1f691; \
    const RemoteGraphic_t* EMOJIS_128276 = &Graphics_bell_1f514; \
    const RemoteGraphic_t* EMOJIS_127904 = &Graphics_carousel_horse_1f3a0; \
    const RemoteGraphic_t* EMOJIS_127905 = &Graphics_ferris_wheel_1f3a1; \
    const RemoteGraphic_t* EMOJIS_129518 = &Graphics_abacus_1f9ee; \
    const RemoteGraphic_t* EMOJIS_129327 = &Graphics_exploding_head_1f92f; \
    const RemoteGraphic_t* EMOJIS_129354 = &Graphics_boxing_glove_1f94a; \
    const RemoteGraphic_t* EMOJIS_129313 = &Graphics_clown_face_1f921; \
    const RemoteGraphic_t* EMOJIS_128640 = &Graphics_rocket_1f680; \
    const RemoteGraphic_t* EMOJIS_127952 = &Graphics_volleyball_1f3d0; \
    const RemoteGraphic_t* EMOJIS_128557 = &Graphics_loudly_crying_face_1f62d; \
    const RemoteGraphic_t* EMOJIS_128535 = &Graphics_kissing_face_1f617; \
    const RemoteGraphic_t* EMOJIS_129296 = &Graphics_zipper_mouth_face_1f910; \
    const RemoteGraphic_t* EMOJIS_9875 = &Graphics_anchor_2693; \
    const RemoteGraphic_t* EMOJIS_128511 = &Graphics_moai_1f5ff; \
    const RemoteGraphic_t* EMOJIS_9200 = &Graphics_alarm_clock_23f0; \
    const RemoteGraphic_t* EMOJIS_129687 = &Graphics_accordion_1fa97; \
    const RemoteGraphic_t* EMOJIS_129398 = &Graphics_cold_face_1f976; \
    const RemoteGraphic_t* EMOJIS_127928 = &Graphics_guitar_1f3b8; \
    const RemoteGraphic_t* EMOJIS_129314 = &Graphics_nauseated_face_1f922; \
    const RemoteGraphic_t* EMOJIS_128125 = &Graphics_alien_1f47d; \
    const RemoteGraphic_t* EMOJIS_128218 = &Graphics_books_1f4da; \
    const RemoteGraphic_t* EMOJIS_128161 = &Graphics_light_bulb_1f4a1; \
    const RemoteGraphic_t* EMOJIS_128563 = &Graphics_flushed_face_1f633; \
    const RemoteGraphic_t* EMOJIS_128141 = &Graphics_ring_1f48d; \
    const RemoteGraphic_t* EMOJIS_128128 = &Graphics_skull_1f480; \
    const RemoteGraphic_t* EMOJIS_128642 = &Graphics_locomotive_1f682; \
    const RemoteGraphic_t* EMOJIS_129312 = &Graphics_cowboy_hat_face_1f920; \
    const RemoteGraphic_t* EMOJIS_128169 = &Graphics_pile_of_poo_1f4a9; \
    const RemoteGraphic_t* EMOJIS_129523 = &Graphics_luggage_1f9f3; \
    const RemoteGraphic_t* EMOJIS_129406 = &Graphics_hiking_boot_1f97e; \
    const RemoteGraphic_t* EMOJIS_128564 = &Graphics_sleeping_face_1f634; \
    const RemoteGraphic_t* EMOJIS_128565 = &Graphics_dizzy_face_1f635; \
    const RemoteGraphic_t* EMOJIS_128561 = &Graphics_face_screaming_in_fear_1f631; \
    const RemoteGraphic_t* EMOJIS_129488 = &Graphics_face_with_monocle_1f9d0; \
    const RemoteGraphic_t* EMOJIS_127890 = &Graphics_backpack_1f392; \
    const RemoteGraphic_t* EMOJIS_127914 = &Graphics_circus_tent_1f3aa; \
    const RemoteGraphic_t* EMOJIS_9999 = &Graphics_pencil_270f_fe0f; \
    const RemoteGraphic_t* EMOJIS_128760 = &Graphics_flying_saucer_1f6f8; \
    const RemoteGraphic_t* EMOJIS_128690 = &Graphics_bicycle_1f6b2; \
    const RemoteGraphic_t* EMOJIS_129326 = &Graphics_face_vomiting_1f92e; \
    const RemoteGraphic_t* EMOJIS_128668 = &Graphics_tractor_1f69c; \
    const RemoteGraphic_t* EMOJIS_128184 = &Graphics_money_with_wings_1f4b8; \
    const RemoteGraphic_t* EMOJIS_129402 = &Graphics_pleading_face_1f97a; \
    const RemoteGraphic_t* EMOJIS_129528 = &Graphics_teddy_bear_1f9f8; \
    const RemoteGraphic_t* EMOJIS_128652 = &Graphics_bus_1f68c; \
    const RemoteGraphic_t* EMOJIS_129299 = &Graphics_nerd_face_1f913; \
    const RemoteGraphic_t* EMOJIS_9973 = &Graphics_sailboat_26f5; \
    const RemoteGraphic_t* EMOJIS_128641 = &Graphics_helicopter_1f681; \
    const RemoteGraphic_t* EMOJIS_129320 = &Graphics_face_with_raised_eyebrow_1f928; \
    const RemoteGraphic_t* EMOJIS_128076 = &Graphics_ok_hand_1f44c; \
    const RemoteGraphic_t* EMOJIS_129302 = &Graphics_robot_1f916; \
    const RemoteGraphic_t* EMOJIS_128734 = &Graphics_wheel_1f6de; \
    const RemoteGraphic_t* EMOJIS_128367 = &Graphics_candle_1f56f_fe0f; \
    const RemoteGraphic_t* EMOJIS_128520 = &Graphics_smiling_face_with_horns_1f608; \
    const RemoteGraphic_t* EMOJIS_9742 = &Graphics_telephone_260e_fe0f; \
    const RemoteGraphic_t* EMOJIS_128551 = &Graphics_anguished_face_1f627;