// This file was generated by generate.py on 2024-06-16 15:43:21.068625

#pragma once

#include <images/connected.h> 
#define UNICODE_GRAPHIC_ICONS_CONNECTED 14408671
#include <images/connecting.h> 
#define UNICODE_GRAPHIC_ICONS_CONNECTING 15471220
#include <images/movie-camera_1f3a5.h> 
#define UNICODE_GRAPHIC_EMOJIS_MOVIE_CAMERA 127909
#include <images/top-hat_1f3a9.h> 
#define UNICODE_GRAPHIC_EMOJIS_TOP_HAT 127913
#include <images/pinched-fingers_1f90c.h> 
#define UNICODE_GRAPHIC_EMOJIS_PINCHED_FINGERS 129292
#include <images/laptop_1f4bb.h> 
#define UNICODE_GRAPHIC_EMOJIS_LAPTOP 128187
#include <images/pool-8-ball_1f3b1.h> 
#define UNICODE_GRAPHIC_EMOJIS_POOL_8_BALL 127921
#include <images/airplane_2708-fe0f.h> 
#define UNICODE_GRAPHIC_EMOJIS_AIRPLANE 9992
#include <images/crown_1f451.h> 
#define UNICODE_GRAPHIC_EMOJIS_CROWN 128081
#include <images/roller-skate_1f6fc.h> 
#define UNICODE_GRAPHIC_EMOJIS_ROLLER_SKATE 128764
#include <images/yarn_1f9f6.h> 
#define UNICODE_GRAPHIC_EMOJIS_YARN 129526
#include <images/smiling-face-with-halo_1f607.h> 
#define UNICODE_GRAPHIC_EMOJIS_SMILING_FACE_WITH_HALO 128519
#include <images/alien-monster_1f47e.h> 
#define UNICODE_GRAPHIC_EMOJIS_ALIEN_MONSTER 128126
#include <images/disguised-face_1f978.h> 
#define UNICODE_GRAPHIC_EMOJIS_DISGUISED_FACE 129400
#include <images/vulcan-salute_1f596-1f3fe_1f3fe.h> 
#define UNICODE_GRAPHIC_EMOJIS_VULCAN_SALUTE_1F596_1F3FE 127998
#include <images/hammer_1f528.h> 
#define UNICODE_GRAPHIC_EMOJIS_HAMMER 128296
#include <images/money-bag_1f4b0.h> 
#define UNICODE_GRAPHIC_EMOJIS_MONEY_BAG 128176
#include <images/trumpet_1f3ba.h> 
#define UNICODE_GRAPHIC_EMOJIS_TRUMPET 127930
#include <images/basketball_1F3C0.h> 
#define UNICODE_GRAPHIC_EMOJIS_BASKETBALL 127936
#include <images/drum_1f941.h> 
#define UNICODE_GRAPHIC_EMOJIS_DRUM 129345
#include <images/astonished-face_1f632.h> 
#define UNICODE_GRAPHIC_EMOJIS_ASTONISHED_FACE 128562
#include <images/ghost_1f47b.h> 
#define UNICODE_GRAPHIC_EMOJIS_GHOST 128123
#include <images/disappointed-face_1f61e.h> 
#define UNICODE_GRAPHIC_EMOJIS_DISAPPOINTED_FACE 128542
#include <images/motorcycle_1f3cd-fe0f.h> 
#define UNICODE_GRAPHIC_EMOJIS_MOTORCYCLE 127949
#include <images/ambulance_1f691.h> 
#define UNICODE_GRAPHIC_EMOJIS_AMBULANCE 128657
#include <images/bell_1f514.h> 
#define UNICODE_GRAPHIC_EMOJIS_BELL 128276
#include <images/carousel-horse_1f3a0.h> 
#define UNICODE_GRAPHIC_EMOJIS_CAROUSEL_HORSE 127904
#include <images/ferris-wheel_1f3a1.h> 
#define UNICODE_GRAPHIC_EMOJIS_FERRIS_WHEEL 127905
#include <images/abacus_1f9ee.h> 
#define UNICODE_GRAPHIC_EMOJIS_ABACUS 129518
#include <images/exploding-head_1f92f.h> 
#define UNICODE_GRAPHIC_EMOJIS_EXPLODING_HEAD 129327
#include <images/boxing-glove_1f94a.h> 
#define UNICODE_GRAPHIC_EMOJIS_BOXING_GLOVE 129354
#include <images/clown-face_1f921.h> 
#define UNICODE_GRAPHIC_EMOJIS_CLOWN_FACE 129313
#include <images/rocket_1f680.h> 
#define UNICODE_GRAPHIC_EMOJIS_ROCKET 128640
#include <images/volleyball_1f3d0.h> 
#define UNICODE_GRAPHIC_EMOJIS_VOLLEYBALL 127952
#include <images/loudly-crying-face_1f62d.h> 
#define UNICODE_GRAPHIC_EMOJIS_LOUDLY_CRYING_FACE 128557
#include <images/kissing-face_1f617.h> 
#define UNICODE_GRAPHIC_EMOJIS_KISSING_FACE 128535
#include <images/zipper-mouth-face_1f910.h> 
#define UNICODE_GRAPHIC_EMOJIS_ZIPPER_MOUTH_FACE 129296
#include <images/anchor_2693.h> 
#define UNICODE_GRAPHIC_EMOJIS_ANCHOR 9875
#include <images/moai_1f5ff.h> 
#define UNICODE_GRAPHIC_EMOJIS_MOAI 128511
#include <images/alarm-clock_23f0.h> 
#define UNICODE_GRAPHIC_EMOJIS_ALARM_CLOCK 9200
#include <images/accordion_1fa97.h> 
#define UNICODE_GRAPHIC_EMOJIS_ACCORDION 129687
#include <images/cold-face_1f976.h> 
#define UNICODE_GRAPHIC_EMOJIS_COLD_FACE 129398
#include <images/guitar_1f3b8.h> 
#define UNICODE_GRAPHIC_EMOJIS_GUITAR 127928
#include <images/nauseated-face_1f922.h> 
#define UNICODE_GRAPHIC_EMOJIS_NAUSEATED_FACE 129314
#include <images/alien_1f47d.h> 
#define UNICODE_GRAPHIC_EMOJIS_ALIEN 128125
#include <images/books_1f4da.h> 
#define UNICODE_GRAPHIC_EMOJIS_BOOKS 128218
#include <images/light-bulb_1f4a1.h> 
#define UNICODE_GRAPHIC_EMOJIS_LIGHT_BULB 128161
#include <images/flushed-face_1f633.h> 
#define UNICODE_GRAPHIC_EMOJIS_FLUSHED_FACE 128563
#include <images/ring_1f48d.h> 
#define UNICODE_GRAPHIC_EMOJIS_RING 128141
#include <images/skull_1f480.h> 
#define UNICODE_GRAPHIC_EMOJIS_SKULL 128128
#include <images/locomotive_1f682.h> 
#define UNICODE_GRAPHIC_EMOJIS_LOCOMOTIVE 128642
#include <images/cowboy-hat-face_1f920.h> 
#define UNICODE_GRAPHIC_EMOJIS_COWBOY_HAT_FACE 129312
#include <images/pile-of-poo_1f4a9.h> 
#define UNICODE_GRAPHIC_EMOJIS_PILE_OF_POO 128169
#include <images/luggage_1f9f3.h> 
#define UNICODE_GRAPHIC_EMOJIS_LUGGAGE 129523
#include <images/hiking-boot_1f97e.h> 
#define UNICODE_GRAPHIC_EMOJIS_HIKING_BOOT 129406
#include <images/sleeping-face_1f634.h> 
#define UNICODE_GRAPHIC_EMOJIS_SLEEPING_FACE 128564
#include <images/dizzy-face_1f635.h> 
#define UNICODE_GRAPHIC_EMOJIS_DIZZY_FACE 128565
#include <images/face-screaming-in-fear_1f631.h> 
#define UNICODE_GRAPHIC_EMOJIS_FACE_SCREAMING_IN_FEAR 128561
#include <images/face-with-monocle_1f9d0.h> 
#define UNICODE_GRAPHIC_EMOJIS_FACE_WITH_MONOCLE 129488
#include <images/backpack_1f392.h> 
#define UNICODE_GRAPHIC_EMOJIS_BACKPACK 127890
#include <images/circus-tent_1f3aa.h> 
#define UNICODE_GRAPHIC_EMOJIS_CIRCUS_TENT 127914
#include <images/pencil_270f-fe0f.h> 
#define UNICODE_GRAPHIC_EMOJIS_PENCIL 9999
#include <images/flying-saucer_1f6f8.h> 
#define UNICODE_GRAPHIC_EMOJIS_FLYING_SAUCER 128760
#include <images/bicycle_1f6b2.h> 
#define UNICODE_GRAPHIC_EMOJIS_BICYCLE 128690
#include <images/face-vomiting_1f92e.h> 
#define UNICODE_GRAPHIC_EMOJIS_FACE_VOMITING 129326
#include <images/tractor_1f69c.h> 
#define UNICODE_GRAPHIC_EMOJIS_TRACTOR 128668
#include <images/money-with-wings_1f4b8.h> 
#define UNICODE_GRAPHIC_EMOJIS_MONEY_WITH_WINGS 128184
#include <images/pleading-face_1f97a.h> 
#define UNICODE_GRAPHIC_EMOJIS_PLEADING_FACE 129402
#include <images/teddy-bear_1f9f8.h> 
#define UNICODE_GRAPHIC_EMOJIS_TEDDY_BEAR 129528
#include <images/bus_1f68c.h> 
#define UNICODE_GRAPHIC_EMOJIS_BUS 128652
#include <images/nerd-face_1f913.h> 
#define UNICODE_GRAPHIC_EMOJIS_NERD_FACE 129299
#include <images/sailboat_26f5.h> 
#define UNICODE_GRAPHIC_EMOJIS_SAILBOAT 9973
#include <images/helicopter_1f681.h> 
#define UNICODE_GRAPHIC_EMOJIS_HELICOPTER 128641
#include <images/face-with-raised-eyebrow_1f928.h> 
#define UNICODE_GRAPHIC_EMOJIS_FACE_WITH_RAISED_EYEBROW 129320
#include <images/ok-hand_1f44c.h> 
#define UNICODE_GRAPHIC_EMOJIS_OK_HAND 128076
#include <images/robot_1f916.h> 
#define UNICODE_GRAPHIC_EMOJIS_ROBOT 129302
#include <images/wheel_1f6de.h> 
#define UNICODE_GRAPHIC_EMOJIS_WHEEL 128734
#include <images/candle_1f56f-fe0f.h> 
#define UNICODE_GRAPHIC_EMOJIS_CANDLE 128367
#include <images/smiling-face-with-horns_1f608.h> 
#define UNICODE_GRAPHIC_EMOJIS_SMILING_FACE_WITH_HORNS 128520
#include <images/telephone_260e-fe0f.h> 
#define UNICODE_GRAPHIC_EMOJIS_TELEPHONE 9742
#include <images/anguished-face_1f627.h> 
#define UNICODE_GRAPHIC_EMOJIS_ANGUISHED_FACE 128551

#define INCLUDE_ALL_IMAGES \
    const RemoteGraphic_t* ICONS_14408671 = &Graphics_icons_connected; \
    const RemoteGraphic_t* ICONS_15471220 = &Graphics_icons_connecting; \
    const RemoteGraphic_t* EMOJIS_127909 = &Graphics_emojis_movie_camera_1f3a5; \
    const RemoteGraphic_t* EMOJIS_127913 = &Graphics_emojis_top_hat_1f3a9; \
    const RemoteGraphic_t* EMOJIS_129292 = &Graphics_emojis_pinched_fingers_1f90c; \
    const RemoteGraphic_t* EMOJIS_128187 = &Graphics_emojis_laptop_1f4bb; \
    const RemoteGraphic_t* EMOJIS_127921 = &Graphics_emojis_pool_8_ball_1f3b1; \
    const RemoteGraphic_t* EMOJIS_9992 = &Graphics_emojis_airplane_2708_fe0f; \
    const RemoteGraphic_t* EMOJIS_128081 = &Graphics_emojis_crown_1f451; \
    const RemoteGraphic_t* EMOJIS_128764 = &Graphics_emojis_roller_skate_1f6fc; \
    const RemoteGraphic_t* EMOJIS_129526 = &Graphics_emojis_yarn_1f9f6; \
    const RemoteGraphic_t* EMOJIS_128519 = &Graphics_emojis_smiling_face_with_halo_1f607; \
    const RemoteGraphic_t* EMOJIS_128126 = &Graphics_emojis_alien_monster_1f47e; \
    const RemoteGraphic_t* EMOJIS_129400 = &Graphics_emojis_disguised_face_1f978; \
    const RemoteGraphic_t* EMOJIS_127998 = &Graphics_emojis_vulcan_salute_1f596_1f3fe_1f3fe; \
    const RemoteGraphic_t* EMOJIS_128296 = &Graphics_emojis_hammer_1f528; \
    const RemoteGraphic_t* EMOJIS_128176 = &Graphics_emojis_money_bag_1f4b0; \
    const RemoteGraphic_t* EMOJIS_127930 = &Graphics_emojis_trumpet_1f3ba; \
    const RemoteGraphic_t* EMOJIS_127936 = &Graphics_emojis_basketball_1F3C0; \
    const RemoteGraphic_t* EMOJIS_129345 = &Graphics_emojis_drum_1f941; \
    const RemoteGraphic_t* EMOJIS_128562 = &Graphics_emojis_astonished_face_1f632; \
    const RemoteGraphic_t* EMOJIS_128123 = &Graphics_emojis_ghost_1f47b; \
    const RemoteGraphic_t* EMOJIS_128542 = &Graphics_emojis_disappointed_face_1f61e; \
    const RemoteGraphic_t* EMOJIS_127949 = &Graphics_emojis_motorcycle_1f3cd_fe0f; \
    const RemoteGraphic_t* EMOJIS_128657 = &Graphics_emojis_ambulance_1f691; \
    const RemoteGraphic_t* EMOJIS_128276 = &Graphics_emojis_bell_1f514; \
    const RemoteGraphic_t* EMOJIS_127904 = &Graphics_emojis_carousel_horse_1f3a0; \
    const RemoteGraphic_t* EMOJIS_127905 = &Graphics_emojis_ferris_wheel_1f3a1; \
    const RemoteGraphic_t* EMOJIS_129518 = &Graphics_emojis_abacus_1f9ee; \
    const RemoteGraphic_t* EMOJIS_129327 = &Graphics_emojis_exploding_head_1f92f; \
    const RemoteGraphic_t* EMOJIS_129354 = &Graphics_emojis_boxing_glove_1f94a; \
    const RemoteGraphic_t* EMOJIS_129313 = &Graphics_emojis_clown_face_1f921; \
    const RemoteGraphic_t* EMOJIS_128640 = &Graphics_emojis_rocket_1f680; \
    const RemoteGraphic_t* EMOJIS_127952 = &Graphics_emojis_volleyball_1f3d0; \
    const RemoteGraphic_t* EMOJIS_128557 = &Graphics_emojis_loudly_crying_face_1f62d; \
    const RemoteGraphic_t* EMOJIS_128535 = &Graphics_emojis_kissing_face_1f617; \
    const RemoteGraphic_t* EMOJIS_129296 = &Graphics_emojis_zipper_mouth_face_1f910; \
    const RemoteGraphic_t* EMOJIS_9875 = &Graphics_emojis_anchor_2693; \
    const RemoteGraphic_t* EMOJIS_128511 = &Graphics_emojis_moai_1f5ff; \
    const RemoteGraphic_t* EMOJIS_9200 = &Graphics_emojis_alarm_clock_23f0; \
    const RemoteGraphic_t* EMOJIS_129687 = &Graphics_emojis_accordion_1fa97; \
    const RemoteGraphic_t* EMOJIS_129398 = &Graphics_emojis_cold_face_1f976; \
    const RemoteGraphic_t* EMOJIS_127928 = &Graphics_emojis_guitar_1f3b8; \
    const RemoteGraphic_t* EMOJIS_129314 = &Graphics_emojis_nauseated_face_1f922; \
    const RemoteGraphic_t* EMOJIS_128125 = &Graphics_emojis_alien_1f47d; \
    const RemoteGraphic_t* EMOJIS_128218 = &Graphics_emojis_books_1f4da; \
    const RemoteGraphic_t* EMOJIS_128161 = &Graphics_emojis_light_bulb_1f4a1; \
    const RemoteGraphic_t* EMOJIS_128563 = &Graphics_emojis_flushed_face_1f633; \
    const RemoteGraphic_t* EMOJIS_128141 = &Graphics_emojis_ring_1f48d; \
    const RemoteGraphic_t* EMOJIS_128128 = &Graphics_emojis_skull_1f480; \
    const RemoteGraphic_t* EMOJIS_128642 = &Graphics_emojis_locomotive_1f682; \
    const RemoteGraphic_t* EMOJIS_129312 = &Graphics_emojis_cowboy_hat_face_1f920; \
    const RemoteGraphic_t* EMOJIS_128169 = &Graphics_emojis_pile_of_poo_1f4a9; \
    const RemoteGraphic_t* EMOJIS_129523 = &Graphics_emojis_luggage_1f9f3; \
    const RemoteGraphic_t* EMOJIS_129406 = &Graphics_emojis_hiking_boot_1f97e; \
    const RemoteGraphic_t* EMOJIS_128564 = &Graphics_emojis_sleeping_face_1f634; \
    const RemoteGraphic_t* EMOJIS_128565 = &Graphics_emojis_dizzy_face_1f635; \
    const RemoteGraphic_t* EMOJIS_128561 = &Graphics_emojis_face_screaming_in_fear_1f631; \
    const RemoteGraphic_t* EMOJIS_129488 = &Graphics_emojis_face_with_monocle_1f9d0; \
    const RemoteGraphic_t* EMOJIS_127890 = &Graphics_emojis_backpack_1f392; \
    const RemoteGraphic_t* EMOJIS_127914 = &Graphics_emojis_circus_tent_1f3aa; \
    const RemoteGraphic_t* EMOJIS_9999 = &Graphics_emojis_pencil_270f_fe0f; \
    const RemoteGraphic_t* EMOJIS_128760 = &Graphics_emojis_flying_saucer_1f6f8; \
    const RemoteGraphic_t* EMOJIS_128690 = &Graphics_emojis_bicycle_1f6b2; \
    const RemoteGraphic_t* EMOJIS_129326 = &Graphics_emojis_face_vomiting_1f92e; \
    const RemoteGraphic_t* EMOJIS_128668 = &Graphics_emojis_tractor_1f69c; \
    const RemoteGraphic_t* EMOJIS_128184 = &Graphics_emojis_money_with_wings_1f4b8; \
    const RemoteGraphic_t* EMOJIS_129402 = &Graphics_emojis_pleading_face_1f97a; \
    const RemoteGraphic_t* EMOJIS_129528 = &Graphics_emojis_teddy_bear_1f9f8; \
    const RemoteGraphic_t* EMOJIS_128652 = &Graphics_emojis_bus_1f68c; \
    const RemoteGraphic_t* EMOJIS_129299 = &Graphics_emojis_nerd_face_1f913; \
    const RemoteGraphic_t* EMOJIS_9973 = &Graphics_emojis_sailboat_26f5; \
    const RemoteGraphic_t* EMOJIS_128641 = &Graphics_emojis_helicopter_1f681; \
    const RemoteGraphic_t* EMOJIS_129320 = &Graphics_emojis_face_with_raised_eyebrow_1f928; \
    const RemoteGraphic_t* EMOJIS_128076 = &Graphics_emojis_ok_hand_1f44c; \
    const RemoteGraphic_t* EMOJIS_129302 = &Graphics_emojis_robot_1f916; \
    const RemoteGraphic_t* EMOJIS_128734 = &Graphics_emojis_wheel_1f6de; \
    const RemoteGraphic_t* EMOJIS_128367 = &Graphics_emojis_candle_1f56f_fe0f; \
    const RemoteGraphic_t* EMOJIS_128520 = &Graphics_emojis_smiling_face_with_horns_1f608; \
    const RemoteGraphic_t* EMOJIS_9742 = &Graphics_emojis_telephone_260e_fe0f; \
    const RemoteGraphic_t* EMOJIS_128551 = &Graphics_emojis_anguished_face_1f627;

#define PRELOAD_ALL_IMAGES \
    PreloadImage(&Graphics_icons_connected); \
    PreloadImage(&Graphics_icons_connecting); \
    PreloadImage(&Graphics_emojis_movie_camera_1f3a5); \
    PreloadImage(&Graphics_emojis_top_hat_1f3a9); \
    PreloadImage(&Graphics_emojis_pinched_fingers_1f90c); \
    PreloadImage(&Graphics_emojis_laptop_1f4bb); \
    PreloadImage(&Graphics_emojis_pool_8_ball_1f3b1); \
    PreloadImage(&Graphics_emojis_airplane_2708_fe0f); \
    PreloadImage(&Graphics_emojis_crown_1f451); \
    PreloadImage(&Graphics_emojis_roller_skate_1f6fc); \
    PreloadImage(&Graphics_emojis_yarn_1f9f6); \
    PreloadImage(&Graphics_emojis_smiling_face_with_halo_1f607); \
    PreloadImage(&Graphics_emojis_alien_monster_1f47e); \
    PreloadImage(&Graphics_emojis_disguised_face_1f978); \
    PreloadImage(&Graphics_emojis_vulcan_salute_1f596_1f3fe_1f3fe); \
    PreloadImage(&Graphics_emojis_hammer_1f528); \
    PreloadImage(&Graphics_emojis_money_bag_1f4b0); \
    PreloadImage(&Graphics_emojis_trumpet_1f3ba); \
    PreloadImage(&Graphics_emojis_basketball_1F3C0); \
    PreloadImage(&Graphics_emojis_drum_1f941); \
    PreloadImage(&Graphics_emojis_astonished_face_1f632); \
    PreloadImage(&Graphics_emojis_ghost_1f47b); \
    PreloadImage(&Graphics_emojis_disappointed_face_1f61e); \
    PreloadImage(&Graphics_emojis_motorcycle_1f3cd_fe0f); \
    PreloadImage(&Graphics_emojis_ambulance_1f691); \
    PreloadImage(&Graphics_emojis_bell_1f514); \
    PreloadImage(&Graphics_emojis_carousel_horse_1f3a0); \
    PreloadImage(&Graphics_emojis_ferris_wheel_1f3a1); \
    PreloadImage(&Graphics_emojis_abacus_1f9ee); \
    PreloadImage(&Graphics_emojis_exploding_head_1f92f); \
    PreloadImage(&Graphics_emojis_boxing_glove_1f94a); \
    PreloadImage(&Graphics_emojis_clown_face_1f921); \
    PreloadImage(&Graphics_emojis_rocket_1f680); \
    PreloadImage(&Graphics_emojis_volleyball_1f3d0); \
    PreloadImage(&Graphics_emojis_loudly_crying_face_1f62d); \
    PreloadImage(&Graphics_emojis_kissing_face_1f617); \
    PreloadImage(&Graphics_emojis_zipper_mouth_face_1f910); \
    PreloadImage(&Graphics_emojis_anchor_2693); \
    PreloadImage(&Graphics_emojis_moai_1f5ff); \
    PreloadImage(&Graphics_emojis_alarm_clock_23f0); \
    PreloadImage(&Graphics_emojis_accordion_1fa97); \
    PreloadImage(&Graphics_emojis_cold_face_1f976); \
    PreloadImage(&Graphics_emojis_guitar_1f3b8); \
    PreloadImage(&Graphics_emojis_nauseated_face_1f922); \
    PreloadImage(&Graphics_emojis_alien_1f47d); \
    PreloadImage(&Graphics_emojis_books_1f4da); \
    PreloadImage(&Graphics_emojis_light_bulb_1f4a1); \
    PreloadImage(&Graphics_emojis_flushed_face_1f633); \
    PreloadImage(&Graphics_emojis_ring_1f48d); \
    PreloadImage(&Graphics_emojis_skull_1f480); \
    PreloadImage(&Graphics_emojis_locomotive_1f682); \
    PreloadImage(&Graphics_emojis_cowboy_hat_face_1f920); \
    PreloadImage(&Graphics_emojis_pile_of_poo_1f4a9); \
    PreloadImage(&Graphics_emojis_luggage_1f9f3); \
    PreloadImage(&Graphics_emojis_hiking_boot_1f97e); \
    PreloadImage(&Graphics_emojis_sleeping_face_1f634); \
    PreloadImage(&Graphics_emojis_dizzy_face_1f635); \
    PreloadImage(&Graphics_emojis_face_screaming_in_fear_1f631); \
    PreloadImage(&Graphics_emojis_face_with_monocle_1f9d0); \
    PreloadImage(&Graphics_emojis_backpack_1f392); \
    PreloadImage(&Graphics_emojis_circus_tent_1f3aa); \
    PreloadImage(&Graphics_emojis_pencil_270f_fe0f); \
    PreloadImage(&Graphics_emojis_flying_saucer_1f6f8); \
    PreloadImage(&Graphics_emojis_bicycle_1f6b2); \
    PreloadImage(&Graphics_emojis_face_vomiting_1f92e); \
    PreloadImage(&Graphics_emojis_tractor_1f69c); \
    PreloadImage(&Graphics_emojis_money_with_wings_1f4b8); \
    PreloadImage(&Graphics_emojis_pleading_face_1f97a); \
    PreloadImage(&Graphics_emojis_teddy_bear_1f9f8); \
    PreloadImage(&Graphics_emojis_bus_1f68c); \
    PreloadImage(&Graphics_emojis_nerd_face_1f913); \
    PreloadImage(&Graphics_emojis_sailboat_26f5); \
    PreloadImage(&Graphics_emojis_helicopter_1f681); \
    PreloadImage(&Graphics_emojis_face_with_raised_eyebrow_1f928); \
    PreloadImage(&Graphics_emojis_ok_hand_1f44c); \
    PreloadImage(&Graphics_emojis_robot_1f916); \
    PreloadImage(&Graphics_emojis_wheel_1f6de); \
    PreloadImage(&Graphics_emojis_candle_1f56f_fe0f); \
    PreloadImage(&Graphics_emojis_smiling_face_with_horns_1f608); \
    PreloadImage(&Graphics_emojis_telephone_260e_fe0f); \
    PreloadImage(&Graphics_emojis_anguished_face_1f627);

#define EMOJI_COUNT 79

const RemoteGraphic_t* GetEmojiByUnicode(uint32_t unicode) {
   if (unicode == 0x1f3a5) return &Graphics_emojis_movie_camera_1f3a5;
   if (unicode == 0x1f3a9) return &Graphics_emojis_top_hat_1f3a9;
   if (unicode == 0x1f90c) return &Graphics_emojis_pinched_fingers_1f90c;
   if (unicode == 0x1f4bb) return &Graphics_emojis_laptop_1f4bb;
   if (unicode == 0x1f3b1) return &Graphics_emojis_pool_8_ball_1f3b1;
   if (unicode == 0x2708) return &Graphics_emojis_airplane_2708_fe0f;
   if (unicode == 0x1f451) return &Graphics_emojis_crown_1f451;
   if (unicode == 0x1f6fc) return &Graphics_emojis_roller_skate_1f6fc;
   if (unicode == 0x1f9f6) return &Graphics_emojis_yarn_1f9f6;
   if (unicode == 0x1f607) return &Graphics_emojis_smiling_face_with_halo_1f607;
   if (unicode == 0x1f47e) return &Graphics_emojis_alien_monster_1f47e;
   if (unicode == 0x1f978) return &Graphics_emojis_disguised_face_1f978;
   if (unicode == 0x1f3fe) return &Graphics_emojis_vulcan_salute_1f596_1f3fe_1f3fe;
   if (unicode == 0x1f528) return &Graphics_emojis_hammer_1f528;
   if (unicode == 0x1f4b0) return &Graphics_emojis_money_bag_1f4b0;
   if (unicode == 0x1f3ba) return &Graphics_emojis_trumpet_1f3ba;
   if (unicode == 0x1f3c0) return &Graphics_emojis_basketball_1F3C0;
   if (unicode == 0x1f941) return &Graphics_emojis_drum_1f941;
   if (unicode == 0x1f632) return &Graphics_emojis_astonished_face_1f632;
   if (unicode == 0x1f47b) return &Graphics_emojis_ghost_1f47b;
   if (unicode == 0x1f61e) return &Graphics_emojis_disappointed_face_1f61e;
   if (unicode == 0x1f3cd) return &Graphics_emojis_motorcycle_1f3cd_fe0f;
   if (unicode == 0x1f691) return &Graphics_emojis_ambulance_1f691;
   if (unicode == 0x1f514) return &Graphics_emojis_bell_1f514;
   if (unicode == 0x1f3a0) return &Graphics_emojis_carousel_horse_1f3a0;
   if (unicode == 0x1f3a1) return &Graphics_emojis_ferris_wheel_1f3a1;
   if (unicode == 0x1f9ee) return &Graphics_emojis_abacus_1f9ee;
   if (unicode == 0x1f92f) return &Graphics_emojis_exploding_head_1f92f;
   if (unicode == 0x1f94a) return &Graphics_emojis_boxing_glove_1f94a;
   if (unicode == 0x1f921) return &Graphics_emojis_clown_face_1f921;
   if (unicode == 0x1f680) return &Graphics_emojis_rocket_1f680;
   if (unicode == 0x1f3d0) return &Graphics_emojis_volleyball_1f3d0;
   if (unicode == 0x1f62d) return &Graphics_emojis_loudly_crying_face_1f62d;
   if (unicode == 0x1f617) return &Graphics_emojis_kissing_face_1f617;
   if (unicode == 0x1f910) return &Graphics_emojis_zipper_mouth_face_1f910;
   if (unicode == 0x2693) return &Graphics_emojis_anchor_2693;
   if (unicode == 0x1f5ff) return &Graphics_emojis_moai_1f5ff;
   if (unicode == 0x23f0) return &Graphics_emojis_alarm_clock_23f0;
   if (unicode == 0x1fa97) return &Graphics_emojis_accordion_1fa97;
   if (unicode == 0x1f976) return &Graphics_emojis_cold_face_1f976;
   if (unicode == 0x1f3b8) return &Graphics_emojis_guitar_1f3b8;
   if (unicode == 0x1f922) return &Graphics_emojis_nauseated_face_1f922;
   if (unicode == 0x1f47d) return &Graphics_emojis_alien_1f47d;
   if (unicode == 0x1f4da) return &Graphics_emojis_books_1f4da;
   if (unicode == 0x1f4a1) return &Graphics_emojis_light_bulb_1f4a1;
   if (unicode == 0x1f633) return &Graphics_emojis_flushed_face_1f633;
   if (unicode == 0x1f48d) return &Graphics_emojis_ring_1f48d;
   if (unicode == 0x1f480) return &Graphics_emojis_skull_1f480;
   if (unicode == 0x1f682) return &Graphics_emojis_locomotive_1f682;
   if (unicode == 0x1f920) return &Graphics_emojis_cowboy_hat_face_1f920;
   if (unicode == 0x1f4a9) return &Graphics_emojis_pile_of_poo_1f4a9;
   if (unicode == 0x1f9f3) return &Graphics_emojis_luggage_1f9f3;
   if (unicode == 0x1f97e) return &Graphics_emojis_hiking_boot_1f97e;
   if (unicode == 0x1f634) return &Graphics_emojis_sleeping_face_1f634;
   if (unicode == 0x1f635) return &Graphics_emojis_dizzy_face_1f635;
   if (unicode == 0x1f631) return &Graphics_emojis_face_screaming_in_fear_1f631;
   if (unicode == 0x1f9d0) return &Graphics_emojis_face_with_monocle_1f9d0;
   if (unicode == 0x1f392) return &Graphics_emojis_backpack_1f392;
   if (unicode == 0x1f3aa) return &Graphics_emojis_circus_tent_1f3aa;
   if (unicode == 0x270f) return &Graphics_emojis_pencil_270f_fe0f;
   if (unicode == 0x1f6f8) return &Graphics_emojis_flying_saucer_1f6f8;
   if (unicode == 0x1f6b2) return &Graphics_emojis_bicycle_1f6b2;
   if (unicode == 0x1f92e) return &Graphics_emojis_face_vomiting_1f92e;
   if (unicode == 0x1f69c) return &Graphics_emojis_tractor_1f69c;
   if (unicode == 0x1f4b8) return &Graphics_emojis_money_with_wings_1f4b8;
   if (unicode == 0x1f97a) return &Graphics_emojis_pleading_face_1f97a;
   if (unicode == 0x1f9f8) return &Graphics_emojis_teddy_bear_1f9f8;
   if (unicode == 0x1f68c) return &Graphics_emojis_bus_1f68c;
   if (unicode == 0x1f913) return &Graphics_emojis_nerd_face_1f913;
   if (unicode == 0x26f5) return &Graphics_emojis_sailboat_26f5;
   if (unicode == 0x1f681) return &Graphics_emojis_helicopter_1f681;
   if (unicode == 0x1f928) return &Graphics_emojis_face_with_raised_eyebrow_1f928;
   if (unicode == 0x1f44c) return &Graphics_emojis_ok_hand_1f44c;
   if (unicode == 0x1f916) return &Graphics_emojis_robot_1f916;
   if (unicode == 0x1f6de) return &Graphics_emojis_wheel_1f6de;
   if (unicode == 0x1f56f) return &Graphics_emojis_candle_1f56f_fe0f;
   if (unicode == 0x1f608) return &Graphics_emojis_smiling_face_with_horns_1f608;
   if (unicode == 0x260e) return &Graphics_emojis_telephone_260e_fe0f;
   if (unicode == 0x1f627) return &Graphics_emojis_anguished_face_1f627;
   return NULL;
}


const RemoteGraphic_t* GetEmojiByIndex(uint16_t index) {
   if (index == 0) return &Graphics_emojis_movie_camera_1f3a5;
   if (index == 1) return &Graphics_emojis_top_hat_1f3a9;
   if (index == 2) return &Graphics_emojis_pinched_fingers_1f90c;
   if (index == 3) return &Graphics_emojis_laptop_1f4bb;
   if (index == 4) return &Graphics_emojis_pool_8_ball_1f3b1;
   if (index == 5) return &Graphics_emojis_airplane_2708_fe0f;
   if (index == 6) return &Graphics_emojis_crown_1f451;
   if (index == 7) return &Graphics_emojis_roller_skate_1f6fc;
   if (index == 8) return &Graphics_emojis_yarn_1f9f6;
   if (index == 9) return &Graphics_emojis_smiling_face_with_halo_1f607;
   if (index == 10) return &Graphics_emojis_alien_monster_1f47e;
   if (index == 11) return &Graphics_emojis_disguised_face_1f978;
   if (index == 12) return &Graphics_emojis_vulcan_salute_1f596_1f3fe_1f3fe;
   if (index == 13) return &Graphics_emojis_hammer_1f528;
   if (index == 14) return &Graphics_emojis_money_bag_1f4b0;
   if (index == 15) return &Graphics_emojis_trumpet_1f3ba;
   if (index == 16) return &Graphics_emojis_basketball_1F3C0;
   if (index == 17) return &Graphics_emojis_drum_1f941;
   if (index == 18) return &Graphics_emojis_astonished_face_1f632;
   if (index == 19) return &Graphics_emojis_ghost_1f47b;
   if (index == 20) return &Graphics_emojis_disappointed_face_1f61e;
   if (index == 21) return &Graphics_emojis_motorcycle_1f3cd_fe0f;
   if (index == 22) return &Graphics_emojis_ambulance_1f691;
   if (index == 23) return &Graphics_emojis_bell_1f514;
   if (index == 24) return &Graphics_emojis_carousel_horse_1f3a0;
   if (index == 25) return &Graphics_emojis_ferris_wheel_1f3a1;
   if (index == 26) return &Graphics_emojis_abacus_1f9ee;
   if (index == 27) return &Graphics_emojis_exploding_head_1f92f;
   if (index == 28) return &Graphics_emojis_boxing_glove_1f94a;
   if (index == 29) return &Graphics_emojis_clown_face_1f921;
   if (index == 30) return &Graphics_emojis_rocket_1f680;
   if (index == 31) return &Graphics_emojis_volleyball_1f3d0;
   if (index == 32) return &Graphics_emojis_loudly_crying_face_1f62d;
   if (index == 33) return &Graphics_emojis_kissing_face_1f617;
   if (index == 34) return &Graphics_emojis_zipper_mouth_face_1f910;
   if (index == 35) return &Graphics_emojis_anchor_2693;
   if (index == 36) return &Graphics_emojis_moai_1f5ff;
   if (index == 37) return &Graphics_emojis_alarm_clock_23f0;
   if (index == 38) return &Graphics_emojis_accordion_1fa97;
   if (index == 39) return &Graphics_emojis_cold_face_1f976;
   if (index == 40) return &Graphics_emojis_guitar_1f3b8;
   if (index == 41) return &Graphics_emojis_nauseated_face_1f922;
   if (index == 42) return &Graphics_emojis_alien_1f47d;
   if (index == 43) return &Graphics_emojis_books_1f4da;
   if (index == 44) return &Graphics_emojis_light_bulb_1f4a1;
   if (index == 45) return &Graphics_emojis_flushed_face_1f633;
   if (index == 46) return &Graphics_emojis_ring_1f48d;
   if (index == 47) return &Graphics_emojis_skull_1f480;
   if (index == 48) return &Graphics_emojis_locomotive_1f682;
   if (index == 49) return &Graphics_emojis_cowboy_hat_face_1f920;
   if (index == 50) return &Graphics_emojis_pile_of_poo_1f4a9;
   if (index == 51) return &Graphics_emojis_luggage_1f9f3;
   if (index == 52) return &Graphics_emojis_hiking_boot_1f97e;
   if (index == 53) return &Graphics_emojis_sleeping_face_1f634;
   if (index == 54) return &Graphics_emojis_dizzy_face_1f635;
   if (index == 55) return &Graphics_emojis_face_screaming_in_fear_1f631;
   if (index == 56) return &Graphics_emojis_face_with_monocle_1f9d0;
   if (index == 57) return &Graphics_emojis_backpack_1f392;
   if (index == 58) return &Graphics_emojis_circus_tent_1f3aa;
   if (index == 59) return &Graphics_emojis_pencil_270f_fe0f;
   if (index == 60) return &Graphics_emojis_flying_saucer_1f6f8;
   if (index == 61) return &Graphics_emojis_bicycle_1f6b2;
   if (index == 62) return &Graphics_emojis_face_vomiting_1f92e;
   if (index == 63) return &Graphics_emojis_tractor_1f69c;
   if (index == 64) return &Graphics_emojis_money_with_wings_1f4b8;
   if (index == 65) return &Graphics_emojis_pleading_face_1f97a;
   if (index == 66) return &Graphics_emojis_teddy_bear_1f9f8;
   if (index == 67) return &Graphics_emojis_bus_1f68c;
   if (index == 68) return &Graphics_emojis_nerd_face_1f913;
   if (index == 69) return &Graphics_emojis_sailboat_26f5;
   if (index == 70) return &Graphics_emojis_helicopter_1f681;
   if (index == 71) return &Graphics_emojis_face_with_raised_eyebrow_1f928;
   if (index == 72) return &Graphics_emojis_ok_hand_1f44c;
   if (index == 73) return &Graphics_emojis_robot_1f916;
   if (index == 74) return &Graphics_emojis_wheel_1f6de;
   if (index == 75) return &Graphics_emojis_candle_1f56f_fe0f;
   if (index == 76) return &Graphics_emojis_smiling_face_with_horns_1f608;
   if (index == 77) return &Graphics_emojis_telephone_260e_fe0f;
   if (index == 78) return &Graphics_emojis_anguished_face_1f627;
   return NULL;
}


