name: platform-io-build-and-test
run-name: Test and Build the Firmware
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./firmware
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/pip
              ~/.platformio/.cache
            key: ${{ runner.os }}-pio
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: Install PlatformIO Core
          run: pip install --upgrade platformio
        # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
        - name: Install platformIO libraries
          run: pio lib install
        - name: Test PlatformIO Project
          run: pio test

  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./firmware
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
                ~/.cache/pip
                ~/.platformio/.cache
            key: ${{ runner.os }}-pio
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: Install PlatformIO Core
          run: pip install --upgrade platformio
        # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
        - name: Install platformIO libraries
          run: pio lib install
        - name: Build PlatformIO Project
          run: pio run